{% set name = "dash-iconify" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_iconify-{{ version }}.tar.gz
  sha256: 564774be6b11b0ac3a8999b7137c3d17a1d351d69b673aa313c7228eacc9d143

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dash

test:
  requires:
    - python {{ python_min }}
  imports:
    - dash_iconify
  # pip checks for dash are broken (https://github.com/conda-forge/dash-mantine-components-feedstock/pull/9#discussion_r1466183308)
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/snehilvj/dash-iconify
  summary: Iconify for Plotly Dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aungriah
